# Site settings
name: Erinç İnci
description: "Software Engineer"
url: "http://erincinci.com/"

# Links
github_username:  erincinci
#codepen_username: your_codepen_username_goes_here
#facebook_username: erincinci
#vk_username: your_vk_username_goes_here
#twitter_username: erincinci
#google_plus_username: erincinci
linkedin_username: erincinci
#vine_username:  your_vine_username_goes_here
#instagram_username:  erincinci
#flickr_username: erincinci
#steam_username: your_steam_username_goes_here
#soundcloud_username:  erincinci
#stack_of_username: erincinci
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: erincinci
#weibo_username: your_weibo_username_goes_here
lastfm_username: erincinci
#blog_url: "/blog"
email: erincinci@gmail.com
public_key_url: "http://pastebin.com/raw/mpLPVJHX"
resume: "https://raw.githubusercontent.com/erincinci/erincinci.github.io/master/CV.pdf"

# Avatar
avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
avatar_img_path: "http://gravatar.com/avatar/afb88512fefbb3363a79e03a3d2eb22e?s=350"

# Front Image
front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Favicon
favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
